swagger: '2.0'
info:
  title: GraphQL API
  description: API for handling GraphQL queries.
  version: 1.0.0
host: quads-nejah-ouerdani.appspot.com
basePath: /_ah/api
schemes:
  - https
paths:
  /graphql/v1/get_most:
    get:
      operationId: get_most
      description: Fetch the most recent RDFTriples from Datastore.
      responses:
        200:
          description: A list of RDF triples
          schema:
            type: array
            items:
              $ref: '#/definitions/RDFTriple'

/graphql/v1/healthCheck:
    get:
      operationId: healthCheck
      description: Check the health status of the API.
      responses:
        200:
          description: API is healthy and deployed.
          schema:
            type: string
            example: "OK"
        500:
          description: API is not functioning properly.
          schema:
            type: string
            example: "Error connecting to the API."

definitions:
  RDFTriple:
    type: object
    properties:
      subject:
        type: string
      predicate:
        type: string
      object:
        type: string
      graph:
        type: string
